/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author zDefcon
 */
public class ConsumoKwGU extends javax.swing.JFrame {

  /**
   * Creates new form ConsumoKwGU
   */
  public ConsumoKwGU() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do
   * NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtTotalAPagar = new javax.swing.JTextField();
    txtKilowats = new javax.swing.JTextField();
    btnSalir = new javax.swing.JButton();
    btnCalcular = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Miracode", 0, 18)); // NOI18N
    jLabel1.setText("Ingrese los kw consumidos en el mes");

    jLabel2.setFont(new java.awt.Font("Miracode", 0, 18)); // NOI18N
    jLabel2.setText("Total a Pagar:");

    jLabel3.setFont(new java.awt.Font("Miracode", 0, 24)); // NOI18N
    jLabel3.setText("Consumo Electrico KW");

    txtTotalAPagar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTotalAPagarActionPerformed(evt);
      }
    });

    txtKilowats.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtKilowatsActionPerformed(evt);
      }
    });

    btnSalir.setFont(new java.awt.Font("Miracode", 0, 18)); // NOI18N
    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    btnCalcular.setFont(new java.awt.Font("Miracode", 0, 18)); // NOI18N
    btnCalcular.setText("Calcular");
    btnCalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCalcularActionPerformed(evt);
      }
    });

    btnLimpiar.setFont(new java.awt.Font("Miracode", 0, 18)); // NOI18N
    btnLimpiar.setText("Limpiar");
    btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimpiarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnSalir)
        .addGap(23, 23, 23))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(153, 153, 153)
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(275, 275, 275)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel2)
                .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txtKilowats, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(202, 202, 202)
            .addComponent(jLabel3))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(297, 297, 297)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(169, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addComponent(btnSalir)
        .addGap(36, 36, 36)
        .addComponent(jLabel3)
        .addGap(42, 42, 42)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(txtKilowats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(49, 49, 49)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40)
        .addComponent(btnCalcular)
        .addGap(27, 27, 27)
        .addComponent(btnLimpiar)
        .addContainerGap(155, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 4, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtTotalAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAPagarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTotalAPagarActionPerformed

  private void txtKilowatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilowatsActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtKilowatsActionPerformed

  private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    int option = JOptionPane.showConfirmDialog(this, "Estas Seguro De Salir De La Ventana?", "Confirmar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if(option == JOptionPane.YES_OPTION){
      System.exit(0);
    }
  }//GEN-LAST:event_btnSalirActionPerformed

  private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    // TODO add your handling code here:
    
     double kw, totalPagar=0;
     String input = txtKilowats.getText();
     // Asignacion De Las Variables A Las Cajas De Texto
     
     try{
     kw = Double.parseDouble(txtKilowats.getText());
     
     if(kw <= 0 && kw >= 150){
       //Calculo Del Total A Pagar
       totalPagar = kw * 0.21;
     }
     else if(kw >= 151 && kw <= 300){
       totalPagar = kw * 1.88;
       
     }
     else if(kw >= 301 && kw <= 600){
       totalPagar = kw * 3.01;
       
     }
     else if(kw >= 601 && kw <= 1800){
       totalPagar = kw * 4.16;
       
     }
     else if(kw >= 1801 && kw <= 3400){
       totalPagar = kw * 187.6;
       
     }
     else if(kw >= 3401 && kw <= 5000){
       totalPagar = kw * 200;
       
     }else{
       JOptionPane.showMessageDialog(this, "El valor Ingresado No Corresponde A Las Tarifas");
       return;
     }
     
     txtTotalAPagar.setText(""+totalPagar);
     
      }catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Porfavor, Ingrese Un Numero Valido", "Error De Entrada", JOptionPane.ERROR_MESSAGE);
        txtKilowats.requestFocus();
      }
 
  }//GEN-LAST:event_btnCalcularActionPerformed

  private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    // TODO add your handling code here:
    txtKilowats.setText("");
    txtTotalAPagar.setText("");
  }//GEN-LAST:event_btnLimpiarActionPerformed

  /**
   * @param args the command line arguments
   */
 

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCalcular;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JButton btnSalir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtKilowats;
  private javax.swing.JTextField txtTotalAPagar;
  // End of variables declaration//GEN-END:variables
}
